{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitea-mirror.serviceAccountName" . }}
  labels:
    {{- include "gitea-mirror.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
      {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}

