name: Nix Build and Cache

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v12
        with:
          name: gitea-mirror  # Your cache name
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build --print-build-logs

      - name: Check flake
        run: nix flake check

      - name: Test run (dry run)
        run: |
          # Just verify the binary exists and is executable
          test -x ./result/bin/gitea-mirror
          ./result/bin/gitea-mirror --version || echo "Version check skipped"
